<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinanceCategoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\FinanceCategory\Controller\FinanceCategoryController' shared autowired service.
     *
     * @return \App\FinanceCategory\Controller\FinanceCategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/FinanceCategory/Controller/FinanceCategoryController.php';
        include_once \dirname(__DIR__, 4).'/src/FinanceCategory/Domain/Service/FinanceCategoryServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/FinanceCategory/Application/Service/FinanceCategoryService.php';

        $container->services['App\\FinanceCategory\\Controller\\FinanceCategoryController'] = $instance = new \App\FinanceCategory\Controller\FinanceCategoryController(new \App\FinanceCategory\Application\Service\FinanceCategoryService(($container->privates['App\\FinanceCategory\\Infrastructure\\Repository\\FinanceCategoryRepository'] ?? $container->load('getFinanceCategoryRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\FinanceCategory\\Controller\\FinanceCategoryController', $container));

        return $instance;
    }
}
