<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinancePlanControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\FinancePlan\Controller\FinancePlanController' shared autowired service.
     *
     * @return \App\FinancePlan\Controller\FinancePlanController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/FinancePlan/Controller/FinancePlanController.php';
        include_once \dirname(__DIR__, 4).'/src/FinancePlan/Domain/Service/FinancePlanServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/FinancePlan/Application/Service/FinancePlanService.php';

        $container->services['App\\FinancePlan\\Controller\\FinancePlanController'] = $instance = new \App\FinancePlan\Controller\FinancePlanController(new \App\FinancePlan\Application\Service\FinancePlanService(($container->privates['App\\FinancePlan\\Infrastructure\\Repository\\FinancePlanRepository'] ?? $container->load('getFinancePlanRepositoryService')), ($container->privates['App\\FinanceCategory\\Infrastructure\\Repository\\FinanceCategoryRepository'] ?? $container->load('getFinanceCategoryRepositoryService')), ($container->privates['App\\Finance\\Infrastructure\\Repository\\FinanceRepository'] ?? $container->load('getFinanceRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\FinancePlan\\Controller\\FinancePlanController', $container));

        return $instance;
    }
}
