<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinanceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Finance\Controller\FinanceController' shared autowired service.
     *
     * @return \App\Finance\Controller\FinanceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Finance/Controller/FinanceController.php';
        include_once \dirname(__DIR__, 4).'/src/Finance/Domain/Service/FinanceServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Finance/Application/Service/FinanceService.php';

        $container->services['App\\Finance\\Controller\\FinanceController'] = $instance = new \App\Finance\Controller\FinanceController(new \App\Finance\Application\Service\FinanceService(($container->privates['App\\Finance\\Infrastructure\\Repository\\FinanceRepository'] ?? $container->load('getFinanceRepositoryService')), ($container->privates['App\\FinanceCategory\\Infrastructure\\Repository\\FinanceCategoryRepository'] ?? $container->load('getFinanceCategoryRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Finance\\Controller\\FinanceController', $container));

        return $instance;
    }
}
