<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthMetricEntryRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\HealthMetricEntry\Infrastructure\Repository\HealthMetricEntryRepository' shared autowired service.
     *
     * @return \App\HealthMetricEntry\Infrastructure\Repository\HealthMetricEntryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricEntry/Domain/Repository/HealthMetricEntryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricEntry/Infrastructure/Repository/HealthMetricEntryRepository.php';

        return $container->privates['App\\HealthMetricEntry\\Infrastructure\\Repository\\HealthMetricEntryRepository'] = new \App\HealthMetricEntry\Infrastructure\Repository\HealthMetricEntryRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
