<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Habit\Infrastructure\Repository\HabitRepository' shared autowired service.
     *
     * @return \App\Habit\Infrastructure\Repository\HabitRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Habit/Domain/Repository/HabitRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Infrastructure/Repository/HabitRepository.php';

        return $container->privates['App\\Habit\\Infrastructure\\Repository\\HabitRepository'] = new \App\Habit\Infrastructure\Repository\HabitRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
