<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthMetricTypeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\HealthMetricType\Infrastructure\Repository\HealthMetricTypeRepository' shared autowired service.
     *
     * @return \App\HealthMetricType\Infrastructure\Repository\HealthMetricTypeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricType/Domain/Repository/HealthMetricTypeRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricType/Infrastructure/Repository/HealthMetricTypeRepository.php';

        return $container->privates['App\\HealthMetricType\\Infrastructure\\Repository\\HealthMetricTypeRepository'] = new \App\HealthMetricType\Infrastructure\Repository\HealthMetricTypeRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
