<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthMetricEntryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\HealthMetricEntry\Controller\HealthMetricEntryController' shared autowired service.
     *
     * @return \App\HealthMetricEntry\Controller\HealthMetricEntryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricEntry/Controller/HealthMetricEntryController.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricEntry/Domain/Service/HealthMetricEntryServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricEntry/Application/Service/HealthMetricEntryService.php';

        $container->services['App\\HealthMetricEntry\\Controller\\HealthMetricEntryController'] = $instance = new \App\HealthMetricEntry\Controller\HealthMetricEntryController(new \App\HealthMetricEntry\Application\Service\HealthMetricEntryService(($container->privates['App\\HealthMetricEntry\\Infrastructure\\Repository\\HealthMetricEntryRepository'] ?? $container->load('getHealthMetricEntryRepositoryService')), ($container->privates['App\\HealthMetricType\\Infrastructure\\Repository\\HealthMetricTypeRepository'] ?? $container->load('getHealthMetricTypeRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\HealthMetricEntry\\Controller\\HealthMetricEntryController', $container));

        return $instance;
    }
}
