<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthMetricTypeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\HealthMetricType\Controller\HealthMetricTypeController' shared autowired service.
     *
     * @return \App\HealthMetricType\Controller\HealthMetricTypeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricType/Controller/HealthMetricTypeController.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricType/Domain/Service/HealthMetricTypeServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/HealthMetricType/Application/Service/HealthMetricTypeService.php';

        $container->services['App\\HealthMetricType\\Controller\\HealthMetricTypeController'] = $instance = new \App\HealthMetricType\Controller\HealthMetricTypeController(new \App\HealthMetricType\Application\Service\HealthMetricTypeService(($container->privates['App\\HealthMetricType\\Infrastructure\\Repository\\HealthMetricTypeRepository'] ?? $container->load('getHealthMetricTypeRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\HealthMetricType\\Controller\\HealthMetricTypeController', $container));

        return $instance;
    }
}
