<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonalStateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\PersonalState\Controller\PersonalStateController' shared autowired service.
     *
     * @return \App\PersonalState\Controller\PersonalStateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/PersonalState/Controller/PersonalStateController.php';
        include_once \dirname(__DIR__, 4).'/src/PersonalState/Domain/Service/PersonalStateServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PersonalState/Application/Service/PersonalStateService.php';

        $container->services['App\\PersonalState\\Controller\\PersonalStateController'] = $instance = new \App\PersonalState\Controller\PersonalStateController(new \App\PersonalState\Application\Service\PersonalStateService(($container->privates['App\\Finance\\Infrastructure\\Repository\\FinanceRepository'] ?? $container->load('getFinanceRepositoryService')), ($container->privates['App\\FinancePlan\\Infrastructure\\Repository\\FinancePlanRepository'] ?? $container->load('getFinancePlanRepositoryService')), ($container->privates['App\\Goal\\Infrastructure\\Repository\\GoalRepository'] ?? $container->load('getGoalRepositoryService')), ($container->privates['App\\Habit\\Infrastructure\\Repository\\HabitRepository'] ?? $container->load('getHabitRepositoryService')), ($container->privates['App\\Task\\Infrastructure\\Repository\\TaskRepository'] ?? $container->load('getTaskRepositoryService')), ($container->privates['App\\HealthMetricEntry\\Infrastructure\\Repository\\HealthMetricEntryRepository'] ?? $container->load('getHealthMetricEntryRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\PersonalState\\Controller\\PersonalStateController', $container));

        return $instance;
    }
}
