<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Statistic\Controller\StatisticController' shared autowired service.
     *
     * @return \App\Statistic\Controller\StatisticController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Statistic/Controller/StatisticController.php';
        include_once \dirname(__DIR__, 4).'/src/Statistic/Domain/Service/StatisticServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Statistic/Application/Service/StatisticService.php';

        $container->services['App\\Statistic\\Controller\\StatisticController'] = $instance = new \App\Statistic\Controller\StatisticController(new \App\Statistic\Application\Service\StatisticService(($container->privates['App\\Goal\\Infrastructure\\Repository\\GoalRepository'] ?? $container->load('getGoalRepositoryService')), ($container->privates['App\\Habit\\Infrastructure\\Repository\\HabitRepository'] ?? $container->load('getHabitRepositoryService')), ($container->privates['App\\Task\\Infrastructure\\Repository\\TaskRepository'] ?? $container->load('getTaskRepositoryService')), ($container->privates['App\\Finance\\Infrastructure\\Repository\\FinanceRepository'] ?? $container->load('getFinanceRepositoryService')), ($container->privates['App\\FinancePlan\\Infrastructure\\Repository\\FinancePlanRepository'] ?? $container->load('getFinancePlanRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Statistic\\Controller\\StatisticController', $container));

        return $instance;
    }
}
