<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Telegram\Controller\TelegramController' shared autowired service.
     *
     * @return \App\Telegram\Controller\TelegramController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/Controller/TelegramController.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/Application/Service/TelegramService.php';

        $container->services['App\\Telegram\\Controller\\TelegramController'] = $instance = new \App\Telegram\Controller\TelegramController(new \App\Telegram\Application\Service\TelegramService(($container->privates['App\\Telegram\\Infrastructure\\Repository\\TelegramLinkTokenRepository'] ?? $container->load('getTelegramLinkTokenRepositoryService')), ($container->privates['App\\User\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['App\\Auth\\Infrastructure\\Repository\\RefreshTokenRepository'] ?? $container->load('getRefreshTokenRepositoryService')), $container->getEnv('default::TELEGRAM_BOT_TOKEN'), $container->getEnv('default::TELEGRAM_BOT_USERNAME'), $container->getEnv('default::TELEGRAM_MINI_APP_URL')), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Telegram\\Controller\\TelegramController', $container));

        return $instance;
    }
}
