<?php

namespace ContainerNHkkVNf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramLinkTokenRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Telegram\Infrastructure\Repository\TelegramLinkTokenRepository' shared autowired service.
     *
     * @return \App\Telegram\Infrastructure\Repository\TelegramLinkTokenRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/Domain/Repository/TelegramLinkTokenRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Telegram/Infrastructure/Repository/TelegramLinkTokenRepository.php';

        return $container->privates['App\\Telegram\\Infrastructure\\Repository\\TelegramLinkTokenRepository'] = new \App\Telegram\Infrastructure\Repository\TelegramLinkTokenRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
