<?php

namespace ContainerEGNUlcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoalRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Goal\Infrastructure\Repository\GoalRepository' shared autowired service.
     *
     * @return \App\Goal\Infrastructure\Repository\GoalRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Goal/Domain/Repository/GoalRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Goal/Infrastructure/Repository/GoalRepository.php';

        return $container->privates['App\\Goal\\Infrastructure\\Repository\\GoalRepository'] = new \App\Goal\Infrastructure\Repository\GoalRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
