<?php

namespace ContainerEGNUlcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaker_DoctrineHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'maker.doctrine_helper' shared service.
     *
     * @return \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Doctrine/DoctrineHelper.php';

        $a = ($container->privates['doctrine.orm.default_attribute_metadata_driver'] ?? $container->load('getDoctrine_Orm_DefaultAttributeMetadataDriverService'));

        return $container->privates['maker.doctrine_helper'] = new \Symfony\Bundle\MakerBundle\Doctrine\DoctrineHelper('App\\Entity', ($container->services['doctrine'] ?? $container->load('getDoctrineService')), ['default' => [['App\\User\\Infrastructure\\Persistence', $a], ['App\\Auth\\Infrastructure\\Persistence', $a], ['App\\Task\\Infrastructure\\Persistence', $a], ['App\\Category\\Infrastructure\\Persistence', $a], ['App\\Goal\\Infrastructure\\Persistence', $a], ['App\\Habit\\Infrastructure\\Persistence', $a], ['App\\Reminder\\Infrastructure\\Persistence', $a]]]);
    }
}
