<?php

namespace ContainerEGNUlcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefreshTokenControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JZG_GAb.App\Auth\Controller\RefreshTokenController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JZG_GAb.App\\Auth\\Controller\\RefreshTokenController::__invoke()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'refreshTokens' => ['privates', 'App\\Auth\\Infrastructure\\Repository\\RefreshTokenRepository', 'getRefreshTokenRepositoryService', true],
            'jwtManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
        ], [
            'refreshTokens' => '?',
            'jwtManager' => '?',
        ]))->withContext('App\\Auth\\Controller\\RefreshTokenController::__invoke()', $container);
    }
}
