<?php

namespace ContainerEGNUlcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Task\Infrastructure\Repository\TaskRepository' shared autowired service.
     *
     * @return \App\Task\Infrastructure\Repository\TaskRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Task/Domain/Repository/TaskRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Task/Infrastructure/Repository/TaskRepository.php';

        return $container->privates['App\\Task\\Infrastructure\\Repository\\TaskRepository'] = new \App\Task\Infrastructure\Repository\TaskRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
