<?php

namespace ContainerYxQJKqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Auth\Infrastructure\EventListener\LoginSuccessListener' shared autowired service.
     *
     * @return \App\Auth\Infrastructure\EventListener\LoginSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Auth/Infrastructure/EventListener/LoginSuccessListener.php';

        return $container->privates['App\\Auth\\Infrastructure\\EventListener\\LoginSuccessListener'] = new \App\Auth\Infrastructure\EventListener\LoginSuccessListener(($container->privates['App\\Auth\\Infrastructure\\Repository\\RefreshTokenRepository'] ?? $container->load('getRefreshTokenRepositoryService')));
    }
}
