<?php

namespace ContainerYxQJKqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ijCeiC6.App\Auth\Controller\LogoutController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ijCeiC6.App\\Auth\\Controller\\LogoutController::__invoke()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'refreshTokens' => ['privates', 'App\\Auth\\Infrastructure\\Repository\\RefreshTokenRepository', 'getRefreshTokenRepositoryService', true],
        ], [
            'security' => '?',
            'refreshTokens' => '?',
        ]))->withContext('App\\Auth\\Controller\\LogoutController::__invoke()', $container);
    }
}
