<?php

namespace ContainerYxQJKqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefreshTokenRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Auth\Infrastructure\Repository\RefreshTokenRepository' shared autowired service.
     *
     * @return \App\Auth\Infrastructure\Repository\RefreshTokenRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/Domain/Repository/RefreshTokenRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/Infrastructure/Repository/RefreshTokenRepository.php';

        return $container->privates['App\\Auth\\Infrastructure\\Repository\\RefreshTokenRepository'] = new \App\Auth\Infrastructure\Repository\RefreshTokenRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
