<?php

namespace ContainerYxQJKqo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\User\Controller\UserController' shared autowired service.
     *
     * @return \App\User\Controller\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/User/Controller/UserController.php';
        include_once \dirname(__DIR__, 4).'/src/User/Domain/Service/UserServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/User/Application/Service/UserService.php';

        $container->services['App\\User\\Controller\\UserController'] = $instance = new \App\User\Controller\UserController(new \App\User\Application\Service\UserService(($container->privates['App\\User\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\User\\Controller\\UserController', $container));

        return $instance;
    }
}
