<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGNUlcx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGNUlcx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGNUlcx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGNUlcx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEGNUlcx\App_KernelDevDebugContainer([
    'container.build_hash' => 'EGNUlcx',
    'container.build_id' => 'b887be63',
    'container.build_time' => 1774246929,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGNUlcx');
