<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxQJKqo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxQJKqo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxQJKqo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxQJKqo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxQJKqo\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxQJKqo',
    'container.build_id' => 'ea1aec9c',
    'container.build_time' => 1768235828,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxQJKqo');
