<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWurfxg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWurfxg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOWurfxg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOWurfxg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOWurfxg\App_KernelDevDebugContainer([
    'container.build_hash' => 'OWurfxg',
    'container.build_id' => '6aa55fbc',
    'container.build_time' => 1774247300,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWurfxg');
