<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_auth_logout__invoke' => [[], ['_controller' => 'App\\Auth\\Controller\\LogoutController'], [], [['text', '/api/auth/logout']], [], [], []],
    'app_auth_refreshtoken__invoke' => [[], ['_controller' => 'App\\Auth\\Controller\\RefreshTokenController'], [], [['text', '/api/auth/refresh']], [], [], []],
    'app_auth_register__invoke' => [[], ['_controller' => 'App\\Auth\\Controller\\RegisterController'], [], [['text', '/api/auth/register']], [], [], []],
    'login_check' => [[], [], [], [['text', '/api/auth/login']], [], [], []],
    'App\Auth\Controller\LogoutController' => [[], ['_controller' => 'App\\Auth\\Controller\\LogoutController'], [], [['text', '/api/auth/logout']], [], [], []],
    'App\Auth\Controller\LogoutController::__invoke' => [[], ['_controller' => 'App\\Auth\\Controller\\LogoutController'], [], [['text', '/api/auth/logout']], [], [], []],
    'App\Auth\Controller\RefreshTokenController' => [[], ['_controller' => 'App\\Auth\\Controller\\RefreshTokenController'], [], [['text', '/api/auth/refresh']], [], [], []],
    'App\Auth\Controller\RefreshTokenController::__invoke' => [[], ['_controller' => 'App\\Auth\\Controller\\RefreshTokenController'], [], [['text', '/api/auth/refresh']], [], [], []],
    'App\Auth\Controller\RegisterController::__invoke' => [[], ['_controller' => 'App\\Auth\\Controller\\RegisterController'], [], [['text', '/api/auth/register']], [], [], []],
    'App\Auth\Controller\RegisterController' => [[], ['_controller' => 'App\\Auth\\Controller\\RegisterController'], [], [['text', '/api/auth/register']], [], [], []],
];
