<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260210220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create reminders table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE reminders (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            title VARCHAR(255) NOT NULL,
            description TEXT DEFAULT NULL,
            entity_type VARCHAR(32) DEFAULT NULL,
            entity_id INT DEFAULT NULL,
            notify_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            frequency VARCHAR(32) NOT NULL DEFAULT \'none\',
            week_days JSON DEFAULT NULL,
            status VARCHAR(32) NOT NULL DEFAULT \'active\',
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_reminders_user ON reminders (user_id)');
        $this->addSql('CREATE INDEX IDX_reminders_notify_at ON reminders (notify_at)');
        $this->addSql('CREATE INDEX IDX_reminders_status ON reminders (status)');
        $this->addSql('ALTER TABLE reminders ADD CONSTRAINT FK_reminders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reminders DROP CONSTRAINT FK_reminders_user');
        $this->addSql('DROP TABLE reminders');
    }
}
