<?php

namespace ContainerOuKp39I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Auth\Controller\LogoutController' shared autowired service.
     *
     * @return \App\Auth\Controller\LogoutController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Auth/Controller/LogoutController.php';

        return $container->services['App\\Auth\\Controller\\LogoutController'] = new \App\Auth\Controller\LogoutController();
    }
}
