<?php

namespace ContainerOuKp39I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O6aUYCb.App\Auth\Controller\RegisterController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O6aUYCb.App\\Auth\\Controller\\RegisterController::__invoke()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'em' => '?',
            'hasher' => '?',
        ]))->withContext('App\\Auth\\Controller\\RegisterController::__invoke()', $container);
    }
}
