export const ROUTES = {
  LOGIN: '/',
  HOME: '/home',
  USER: '/user',
  USERS: '/users',
  TASKS: '/tasks',
  FINANCES: '/finances',
  HEALTH: '/health',
  GOALS: '/goals',
  HABITS: '/habits',
  SETTINGS: '/settings',
  SETTINGS_CATEGORIES: '/settings/categories',
  SETTINGS_FINANCE_CATEGORIES: '/settings/finance-categories',
  SETTINGS_HEALTH_METRICS: '/settings/health-metrics',
}

export const ROUTE_NAMES = {
  LOGIN: 'Login',
  HOME: 'Home',
  USER: 'User',
  USERS: 'Users',
  TASKS: 'Tasks',
  FINANCES: 'Finances',
  HEALTH: 'Health',
  GOALS: 'Goals',
  HABITS: 'Habits',
  SETTINGS: 'Settings',
  SETTINGS_CATEGORIES: 'SettingsCategories',
  SETTINGS_FINANCE_CATEGORIES: 'SettingsFinanceCategories',
  SETTINGS_HEALTH_METRICS: 'SettingsHealthMetrics',
}
