<?php

namespace ContainerWmATx2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Category\Controller\CategoryController' shared autowired service.
     *
     * @return \App\Category\Controller\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Category/Controller/CategoryController.php';
        include_once \dirname(__DIR__, 4).'/src/Category/Domain/Service/CategoryServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Category/Application/Service/CategoryService.php';

        $container->services['App\\Category\\Controller\\CategoryController'] = $instance = new \App\Category\Controller\CategoryController(new \App\Category\Application\Service\CategoryService(($container->privates['App\\Category\\Infrastructure\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Category\\Controller\\CategoryController', $container));

        return $instance;
    }
}
