<?php

namespace ContainerWmATx2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Goal\Controller\GoalController' shared autowired service.
     *
     * @return \App\Goal\Controller\GoalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Goal/Controller/GoalController.php';
        include_once \dirname(__DIR__, 4).'/src/Goal/Domain/Service/GoalServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Goal/Application/Service/GoalService.php';

        $container->services['App\\Goal\\Controller\\GoalController'] = $instance = new \App\Goal\Controller\GoalController(new \App\Goal\Application\Service\GoalService(($container->privates['App\\Goal\\Infrastructure\\Repository\\GoalRepository'] ?? $container->load('getGoalRepositoryService')), ($container->privates['App\\Category\\Infrastructure\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Goal\\Controller\\GoalController', $container));

        return $instance;
    }
}
