<?php

namespace ContainerWmATx2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkSkippedHabitLogsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Habit\Application\Command\MarkSkippedHabitLogsCommand' shared autowired service.
     *
     * @return \App\Habit\Application\Command\MarkSkippedHabitLogsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Application/Command/MarkSkippedHabitLogsCommand.php';

        $container->privates['App\\Habit\\Application\\Command\\MarkSkippedHabitLogsCommand'] = $instance = new \App\Habit\Application\Command\MarkSkippedHabitLogsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:habits:mark-skipped');
        $instance->setDescription('Пометить просроченные pending-логи привычек как skipped');

        return $instance;
    }
}
