<?php

namespace ContainerWmATx2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReminderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Reminder\Controller\ReminderController' shared autowired service.
     *
     * @return \App\Reminder\Controller\ReminderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Controller/ReminderController.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Domain/Service/ReminderServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Application/Service/ReminderService.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Domain/Repository/ReminderRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Infrastructure/Repository/ReminderRepository.php';

        $container->services['App\\Reminder\\Controller\\ReminderController'] = $instance = new \App\Reminder\Controller\ReminderController(new \App\Reminder\Application\Service\ReminderService(new \App\Reminder\Infrastructure\Repository\ReminderRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Reminder\\Controller\\ReminderController', $container));

        return $instance;
    }
}
