<?php

namespace ContainerWmATx2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Task\Controller\TaskController' shared autowired service.
     *
     * @return \App\Task\Controller\TaskController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Task/Controller/TaskController.php';
        include_once \dirname(__DIR__, 4).'/src/Task/Domain/Service/TaskServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Task/Application/Service/TaskService.php';

        $container->services['App\\Task\\Controller\\TaskController'] = $instance = new \App\Task\Controller\TaskController(new \App\Task\Application\Service\TaskService(($container->privates['App\\Task\\Infrastructure\\Repository\\TaskRepository'] ?? $container->load('getTaskRepositoryService')), ($container->privates['App\\User\\Infrastructure\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Goal\\Infrastructure\\Repository\\GoalRepository'] ?? $container->load('getGoalRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Task\\Controller\\TaskController', $container));

        return $instance;
    }
}
