<?php

namespace ContainerXxuKDoc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OwzNfEOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.OwzNfEO' shared service.
     *
     * @return \App\Auth\Infrastructure\Security\RefreshTokenGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Auth\\Controller\\RefreshTokenController::__invoke()": the $generator argument is type-hinted with the non-existent class or interface: "App\\Auth\\Infrastructure\\Security\\RefreshTokenGenerator".');
    }
}
