<?php

namespace ContainerXxuKDoc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OyU6nkcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OyU6nkc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OyU6nkc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Auth\\Controller\\LogoutController::__invoke' => ['privates', '.service_locator.ijCeiC6.App\\Auth\\Controller\\LogoutController::__invoke()', 'getLogoutControllerInvokeService', true],
            'App\\Auth\\Controller\\RefreshTokenController::__invoke' => ['privates', '.service_locator.hj9n2Lm.App\\Auth\\Controller\\RefreshTokenController::__invoke()', 'getRefreshTokenControllerInvokeService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Auth\\Controller\\LogoutController:__invoke' => ['privates', '.service_locator.ijCeiC6.App\\Auth\\Controller\\LogoutController::__invoke()', 'getLogoutControllerInvokeService', true],
            'App\\Auth\\Controller\\LogoutController' => ['privates', '.service_locator.ijCeiC6.App\\Auth\\Controller\\LogoutController::__invoke()', 'getLogoutControllerInvokeService', true],
            'App\\Auth\\Controller\\RefreshTokenController:__invoke' => ['privates', '.service_locator.hj9n2Lm.App\\Auth\\Controller\\RefreshTokenController::__invoke()', 'getRefreshTokenControllerInvokeService', true],
            'App\\Auth\\Controller\\RefreshTokenController' => ['privates', '.service_locator.hj9n2Lm.App\\Auth\\Controller\\RefreshTokenController::__invoke()', 'getRefreshTokenControllerInvokeService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Auth\\Controller\\LogoutController::__invoke' => '?',
            'App\\Auth\\Controller\\RefreshTokenController::__invoke' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Auth\\Controller\\LogoutController:__invoke' => '?',
            'App\\Auth\\Controller\\LogoutController' => '?',
            'App\\Auth\\Controller\\RefreshTokenController:__invoke' => '?',
            'App\\Auth\\Controller\\RefreshTokenController' => '?',
        ]);
    }
}
