<?php

namespace ContainerXxuKDoc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefreshTokenControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hj9n2Lm.App\Auth\Controller\RefreshTokenController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hj9n2Lm.App\\Auth\\Controller\\RefreshTokenController::__invoke()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'refreshTokens' => ['privates', 'App\\Auth\\Infrastructure\\Repository\\RefreshTokenRepository', 'getRefreshTokenRepositoryService', true],
            'jwtManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
            'generator' => ['privates', '.errored.OwzNfEO', NULL, 'Cannot determine controller argument for "App\\Auth\\Controller\\RefreshTokenController::__invoke()": the $generator argument is type-hinted with the non-existent class or interface: "App\\Auth\\Infrastructure\\Security\\RefreshTokenGenerator".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'refreshTokens' => '?',
            'jwtManager' => '?',
            'generator' => '?',
            'security' => '?',
        ]))->withContext('App\\Auth\\Controller\\RefreshTokenController::__invoke()', $container);
    }
}
