<?php

namespace ContainerOWurfxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Category\Infrastructure\Repository\CategoryRepository' shared autowired service.
     *
     * @return \App\Category\Infrastructure\Repository\CategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Category/Domain/Repository/CategoryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Category/Infrastructure/Repository/CategoryRepository.php';

        return $container->privates['App\\Category\\Infrastructure\\Repository\\CategoryRepository'] = new \App\Category\Infrastructure\Repository\CategoryRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
