<?php

namespace ContainerOWurfxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultAttributeMetadataDriverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.default_attribute_metadata_driver' shared service.
     *
     * @return \Doctrine\ORM\Mapping\Driver\AttributeDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/Mapping/Driver/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/Mapping/Driver/ColocatedMappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/Driver/ReflectionBasedDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/Driver/AttributeDriver.php';

        return $container->privates['doctrine.orm.default_attribute_metadata_driver'] = new \Doctrine\ORM\Mapping\Driver\AttributeDriver([(\dirname(__DIR__, 4).'/src/User/Infrastructure/Persistence'), (\dirname(__DIR__, 4).'/src/Auth/Infrastructure/Persistence'), (\dirname(__DIR__, 4).'/src/Task/Infrastructure/Persistence'), (\dirname(__DIR__, 4).'/src/Category/Infrastructure/Persistence'), (\dirname(__DIR__, 4).'/src/Goal/Infrastructure/Persistence'), (\dirname(__DIR__, 4).'/src/Habit/Infrastructure/Persistence'), (\dirname(__DIR__, 4).'/src/Reminder/Infrastructure/Persistence')]);
    }
}
