<?php

namespace ContainerOWurfxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Habit\Controller\HabitController' shared autowired service.
     *
     * @return \App\Habit\Controller\HabitController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Controller/HabitController.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Domain/Service/HabitServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Application/Service/HabitService.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Domain/Repository/HabitRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Habit/Infrastructure/Repository/HabitRepository.php';

        $container->services['App\\Habit\\Controller\\HabitController'] = $instance = new \App\Habit\Controller\HabitController(new \App\Habit\Application\Service\HabitService(new \App\Habit\Infrastructure\Repository\HabitRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))), ($container->privates['App\\Category\\Infrastructure\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['App\\Goal\\Infrastructure\\Repository\\GoalRepository'] ?? $container->load('getGoalRepositoryService'))), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Habit\\Controller\\HabitController', $container));

        return $instance;
    }
}
