<?php

namespace ContainerOWurfxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReminderRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Reminder\Infrastructure\Repository\ReminderRepository' shared autowired service.
     *
     * @return \App\Reminder\Infrastructure\Repository\ReminderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Reminder/Domain/Repository/ReminderRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Infrastructure/Repository/ReminderRepository.php';

        return $container->privates['App\\Reminder\\Infrastructure\\Repository\\ReminderRepository'] = new \App\Reminder\Infrastructure\Repository\ReminderRepository(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
