<?php

namespace ContainerOWurfxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendDueReminderEmailsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Reminder\Application\Command\SendDueReminderEmailsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Reminder\\Application\\Command\\SendDueReminderEmailsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:reminders:send-due-emails', [], 'Отправить e-mail по всем активным напоминаниям, у которых наступило время (notify_at <= now)', false, #[\Closure(name: 'App\\Reminder\\Application\\Command\\SendDueReminderEmailsCommand')] fn (): \App\Reminder\Application\Command\SendDueReminderEmailsCommand => ($container->privates['App\\Reminder\\Application\\Command\\SendDueReminderEmailsCommand'] ?? $container->load('getSendDueReminderEmailsCommandService')));
    }
}
