<?php

namespace ContainerOWurfxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendDueReminderEmailsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Reminder\Application\Command\SendDueReminderEmailsCommand' shared autowired service.
     *
     * @return \App\Reminder\Application\Command\SendDueReminderEmailsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Application/Command/SendDueReminderEmailsCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Reminder/Application/Service/ReminderDueEmailSender.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';

        $container->privates['App\\Reminder\\Application\\Command\\SendDueReminderEmailsCommand'] = $instance = new \App\Reminder\Application\Command\SendDueReminderEmailsCommand(new \App\Reminder\Application\Service\ReminderDueEmailSender(($container->privates['App\\Reminder\\Infrastructure\\Repository\\ReminderRepository'] ?? $container->load('getReminderRepositoryService')), new \Symfony\Component\Mailer\Mailer(($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService')), NULL, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container))), $container->getEnv('MAILER_FROM'), ($container->privates['logger'] ?? self::getLoggerService($container))));

        $instance->setName('app:reminders:send-due-emails');
        $instance->setDescription('Отправить e-mail по всем активным напоминаниям, у которых наступило время (notify_at <= now)');

        return $instance;
    }
}
